### ISSUE TITLE
캡션과 서브캡션 관련해서 추가하면 되는 코드입니다!

### ISSUE THREAD

**Issue by luvehayoung** [QuadFlask/react-native-naver-map#1]
네이버 지도 api를 사용하는것에 정말 큰 도움을 받았구요, 덕분에 지도의 마커에 캡션과 서브캡션을 쉽게 추가할 수 있었습니다. 필요한 분들을 위해서 코드를 공유하려고 합니다!

RNNaverMapMarkerManager 파일 react-native-nmap 폴더안에 있음

//내가 추가하는 부분 시작// @ReactProp(name = "caption" ) public void setCaptionText(RNNaverMapMarker view, String message) { view.setCaptionText(message); }

@ReactProp(name = "subcaption" ) public void setSubCaptionText(RNNaverMapMarker view, String message) { view.setSubCaptionText(message); }

// 내가 추가하는 부분 끝//

RNNaverMapMarker //내가 추가하는 부분 시작// public void setCaptionText(String message) { feature.setCaptionText(message); feature.setCaptionAlign(Align.Top); feature.setCaptionTextSize(25); feature.setCaptionColor(Color.BLUE); feature.setCaptionHaloColor(Color.rgb(255, 255, 255)); }

public void setSubCaptionText(String message) { feature.setSubCaptionText(message); feature.setSubCaptionTextSize(16); feature.setSubCaptionColor(Color.BLUE); feature.setSubCaptionHaloColor(Color.rgb(255, 255, 255)); }

//내가 추가하는 부분 끝//

이렇게 하면 태그에서
<Marker caption = {"내용"} subcaption = {"내용"} ></Marker> 라는 방식으로 캡션도 띄울수가 있더라구요!

**Comment by QuadFlask** [comment]
감사합니다!

현재 안드로이드에 한해서 해당 구현을 추가하였습니다.
