### ISSUE TITLE
해당 examlple ios 실행시 Invariant Violation 에러가 발생합니다.

### ISSUE THREAD

**Issue by taejalove** [QuadFlask/react-native-naver-map#10]
![스크린샷 2020-01-30 오후 5 10 05](https://user-images.githubusercontent.com/59554406/73431289-673c4000-4383-11ea-833c-405eac29c4cb.png)

2020년 1월 30일자 기준 소스 다운받았습니다.

ios 시뮬레이터에서 Invariant Violation: View config not found for name RNNaverMapCircleOverlay.

app.js에서 Circle 제거시에는 정상 동작합니다.

안드로이드에서는 정상 동작합니다.

**Comment by obzect7** [comment]
안드로이드에서도 동일 증상 발생합니다.

**Comment by kirhim** [comment]
저도 같은 에러 발생 합니다

**Comment by QuadFlask** [comment]
ios에 Circle 을 추가하지 않아서 생기는 문제인것 같습니다. 빠른 시일내에 추가하도록 하겠습니다.
