### ISSUE TITLE
현위치 추적과 현위치 오버레이에 대한 질문

### ISSUE THREAD

**Issue by lazyflog** [QuadFlask/react-native-naver-map#124]
### Version of react-native-naver-map libraries

0.0.66

### Version of react-native

0.64.2

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

setLocationTrackingMode().Follow를 호출한 후 API나 제스처를 사용해 임의로 카메라를 움직일 경우 모드가 NoFollow로 바뀌는데, 그 때 위치 추적이 활성화 된 후 사용자의 위치가 이동함에 따라 오버레이가 움직여야함

### Actual behavior

모드가 NoFollow로 바뀐 후 위치 추적이 활성화 된것 같지만 위치 오버레이는 사용자의 위치에 따라 움직이지 않음

### Tested environment (Emulator? Real Device?)

아마 모든기기일것 같습니다.

### Screen Shot

<img width="367" alt="image" src="https://user-images.githubusercontent.com/49199496/143160406-aa7c13d6-ff8c-4670-b02f-663b84415345.png">

**Comment by HuriHuchi** [comment]
같은 이슈를 겪고 있습니다ㅜ 혹시 해결하신 분 계실까요?

**Comment by carpediem0804** [comment]
혹시 있으신가요.....?

**Comment by qnrjs42** [comment]
저도 같은 이슈를 겪고 있는데 임시적으로 이렇게 사용하고 있습니다.
로직은 이렇습니다.

1. gps 값을 계속 추적
2. 추적한 값은 redux에 저장
3. 지도에서 gps 값 바뀔 때마다 setLocationTrackingMode 설정

```
// useMyLocation.ts

import Geolocation from 'react-native-geolocation-service';

useEffect(() => {
    const watchId = isLoggedIn
      ? Geolocation.watchPosition(
          position => {
            handleSetMyLocation(position.coords);
          },
          undefined,
          {
            enableHighAccuracy: true,
            distanceFilter: 5, // 5미터
            interval: 1000 * 1 * 60 * 5, // 5분 캐시 (android)
          },
        )
      : 0;

    return () => {
      if (isLoggedIn) {
        Geolocation.clearWatch(watchId);
      }
    };
  }, [isLoggedIn, handleSetMyLocation]);
```

```
// naverMap.tsx

const currentUserMyLocation = useAppSelector<INaverMapMyLocation | null>(
    state => state.user.myLocation,
  );

useEffect(() => {
  if (mapRef?.current && currentUserMyLocation !== null) {
    mapRef.current.setLocationTrackingMode(2); // 내 위치 아이콘
  }
}, [currentUserMyLocation]);
```

**Comment by qnrjs42** [comment]
저도 같은 이슈를 겪고 있는데 2가지 대체방안이 있지만 전 첫 번째 대체방안 적용 중입니다.

1. icon heading 없이 위치 아이콘 추적하는 방법 (테스트 O)
2. 커스텀 아이콘을 제작하여 위치 아이콘 추적하는 방법 (테스트 X)


## 1. icon heading 없이 위치 아이콘 추적하는 방법
  1. 내 위치 값 리덕스에 저장
  2. 지도에서 리덕스에 저장한 내 위치 값 불러와 위치 아이콘 렌더링

https://navermaps.github.io/ios-map-sdk/guide-ko/4-2.html


`setLocationTrackingMode()`는 2 또는 3으로 설정할 경우 카메라가 센터로 움직이고, 1로 설정할 경우 카메라가 움직이지 않습니다.

그래서 내 위치 값이 바뀔 때마다 1로 설정해 카메라가 센터로 가지 않으면서 위치 아이콘을 추적할 수 있습니다.
다만, heading이 추적 되지 않아 아쉬운 점이 있습니다.


```ts
// useMyLocation.ts

import _debounce from 'lodash/debounce';
import { useDispatch } from 'react-redux';
import { useCallback, useEffect } from 'react';
import Geolocation from 'react-native-geolocation-service';

import userSlice from '@slices/user';
import useAppSelector from '@hooks/useAppSelector';

const useMyLocation = (): void => {
  const dispatch = useDispatch();
  const isLoggedIn = useAppSelector<boolean>(state => state.user.isLoggedIn);

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const handleSetMyLocation = useCallback(
    _debounce(async (coords): Promise<void> => {
      const myCoords = {
        lat: coords.latitude,
        lng: coords.longitude,
      };
      dispatch(userSlice.actions.SET_MYLOCATION(myCoords));
    }, 500),
    [dispatch],
  );

  useEffect(() => {
    const watchId: number = isLoggedIn
      ? Geolocation.watchPosition(
          position => {
            handleSetMyLocation(position.coords);
          },
          undefined,
          {
            enableHighAccuracy: true,
            distanceFilter: 15, // 15미터
            interval: 1000 * 1 * 60 * 5, // 5분 캐시 (android)
          },
        )
      : 0;

    return (): void => {
      if (isLoggedIn) Geolocation.clearWatch(watchId);
    };
  }, [isLoggedIn, handleSetMyLocation]);
};

export default useMyLocation;
```

```tsx
// naverMap.tsx

const currentUserMyLocation = useAppSelector<INaverMapMyLocation | null>(
  state => state.user.myLocation,
);

const handleSetLocationTrackingMode = useCallback((mapRef: any, mode: 1 | 2 = 2): void => {
  mapRef.current?.setLocationTrackingMode(mode); // 내 위치 아이콘
}, []);

// 내 위치 아이콘 리렌더링
useEffect((): void => {
  if (mapRef?.current && currentUserMyLocation !== null) {
    handleSetLocationTrackingMode(mapRef, 1);
  }
}, [currentUserMyLocation, handleSetLocationTrackingMode]);
```


## 2. 커스텀 아이콘을 제작하여 위치 아이콘 추적하는 방법

전에 한 번 시도 하려다가 heading 추적이 쉽지 않아 시간상 포기했었습니다.

react-native-device-heading 라이브러리도 2년 전이 마지막 업데이트이고, 평균 다운르도 수도 적어서 사용하기 꺼림칙하기 때문에 이 부분은 넘어갔습니다.

react-native-geolocation-service 라이브러리도 heading 값을 리턴하지만 -1이 고정 값입니다.
https://github.com/Agontuk/react-native-geolocation-service/issues/59

https://navermaps.github.io/ios-map-sdk/guide-ko/5-5.html

공식문서에서 위치 오버레이 기능이 있지만 react-native-nmap은 해당 기능을 포함하지 않고 있습니다.
기능 활성화를 하려면 네이티브 코드를 건드릴 수 밖에 없는 거 같습니다. (포기..)

**Comment by qja0707** [comment]
ios nmap sdk 3.16.1 에서 해당 버그가 fix 되었다고 합니다.
https://github.com/navermaps/ios-map-sdk/blob/master/CHANGELOG.md#3161

**Comment by lazyflog** [comment]
@qja0707 님의 말씀처럼 해당 버전에서 오류가 Fix 되었기에 이 이슈는 닫겠습니다.
