### ISSUE TITLE
IOS에서 실행시 지도가 나타나지 않는 현상이 있습니다.

### ISSUE THREAD

**Issue by devnok** [QuadFlask/react-native-naver-map#16]
안드로이드에서는 정상작동하지만,
IOS에서는 지도가 제대로 나오지 않네요

처음 nmap(v0.0.40)을 사용할 때는 빌드가 제되로 되지 않아
NMapsMap의 버전을 강제로 3.7.0 올려주어 해결했지만
지도가 제대로 나타나지 않아 nmap의 버전을 0.0.38로 내렸는데도 해결이 되지 않네요 ㅠ
심지어 center, onMapClick등의 props도 제대로 적용되지 않습니다.
해결부탁드립니다.

react-native : 0.61.5
react-native-nmap : 0.0.40 ( 0.0.38 에서도 똑같은 문제발생 )

![image](https://user-images.githubusercontent.com/48426972/77415323-a4fa9980-6e05-11ea-974b-97a1dd6cdff3.png)

**Comment by QuadFlask** [comment]
`NMFClientId`를 등록하신건가요?

**Comment by devnok** [comment]
아 info.plist에 추가하는 과정에서 오타가 났었네요..
수정 후 제대로 나옵니다
