### ISSUE TITLE
property 'line' not found _realOverlay.line

### ISSUE THREAD

**Issue by lyasee** [QuadFlask/react-native-naver-map#17]
version:
react-native: 0.62

error log: 
/node_modules/react-native-nmap/ios/reactNativeNMap/RNNaverMapPolylineOverlay.m:39:16: error: property 'line' not found on object of type 'NMFPolylineOverlay *'
  _realOverlay.line = [NMGLineString lineStringWithPoints:coordinates];
               ^
1 error generated.

NMapsMap 버전을 3.3.0 에서 3.7.0 으로 올린후에 오류 없이 실행됩니다.
3.3.0 버전에서 해결할 수 있는 방법이 있을까요?

**Comment by QuadFlask** [comment]
naver map ios sdk 의 과거 버전 문서를 볼 수 없어 정확하진 않지만 `points` 속성이었던것 같습니다.
[api reference](https://navermaps.github.io/ios-map-sdk/reference/Classes/NMFPolylineOverlay.html#/c:objc(cs)NMFPolylineOverlay(py)line)
[iOS 가이드 문서](https://navermaps.github.io/ios-map-sdk/guide-ko/5-4.html)
```
NSMutableArray<NMGLatLng *> *points = [NSMutableArray arrayWithArray:polyline.points];
polyline.points = points;
```
처럼 작성 할 수 있을것 같습니다.

**Comment by lyasee** [comment]
감사합니다.
저 오류가 모든 polyline 부분에서 전부다 뜨고있어서 3.3.0에서 해결이 안되서 3.7.0 으로 쓰고있는데요.
ios 에서 onTouch, onCameraChange, onMapClick 이벤트들이 동작하지 않는것 같습니다.
혹시 최신버전으로 업데이트하실 계획이 있으신가요?

**Comment by QuadFlask** [comment]
ios 이벤트 바인딩이 제대로 구현되지 않았네요. 수정하도록 하겠습니다.

**Comment by QuadFlask** [comment]
0.0.43 버전에서 수정하였습니다.
