### ISSUE TITLE
동작하지 않는 props 가 있습니다.

### ISSUE THREAD

**Issue by lyasee** [QuadFlask/react-native-naver-map#18]
이전 오류도 빠르게 수정해주셔서 감사합니다.
해당 라이브러리를 사용중에 있어서 동작하지 않는 props 가 있습니다.
NMapsMap 3.7.0 버전 업데이트 되면서 동작하지 않는 것 같습니다.

**NaverMapView**

**ios**
- onInitialized 
- showsMyLocationButton 
- zoomControl 
- scaleBar 
- nightMode 
  
**android**
- onCameraChange  
- nightMode

**Comment by QuadFlask** [comment]
0.0.44 버전에 아래와 같이 수정하였습니다.

## iOS
- ios에서는 android sdk와 달리 `OnMapReadyCallback`이 존재하지 않아 따로 초기화 이벤트를 받을 수 없는것 같습니다.
- `showsMyLocationButton`, `zoomControl`, `scaleBar` 속성 설정 버그를 수정하였습니다.
- `nightMode`의 경우 `Navi` 지도유형만 지원한다고 합니다. ([문서 - 야간모드](https://navermaps.github.io/android-map-sdk/guide-ko/2-3.html)) `mapType` 을 `MapType.Navi`로 설정하신뒤 확인해주세요.

## Android
- onCameraChange 는 퍼포먼스를 위해 컴포넌트 메소드 `watchCameraChange`를 호출해 리스너를 등록했을 경우에만 동작하도록 구현했었으나 camera idle 일 경우에만 호출되는 메소드라 맵 초기화시 등록하도록 수정하였습니다.
