### ISSUE TITLE
requirenativecomponent "~~" was not found in the uimanager 

### ISSUE THREAD

**Issue by lhg1628** [QuadFlask/react-native-naver-map#19]
안녕하세요. 

우선 이렇게 모듈을 제작해주셔서 정말 감사합니다.

제가 만들어주신 모듈을 사용하려고 테스트를 해보았는데,

RN 0.61.2 버전에서는 동작을 확인했는데, 지도화면 - 다른화면 - 지도화면 순으로 전환하면, 앱이 튕겨버리는 버그가 발생합니다.(그냥 아무것도 없는 빈페이지 라우팅으로 테스트 하였습니다.)

그리고 RN 윗버전(0.61.4~)부터는 제목과 같은 에러가 발생합니다.
const RNNaverMapView = requireNativeComponent('RNNaverMapView');
const RNNaverMapMarker = requireNativeComponent('RNNaverMapMarker');
const RNNaverMapPathOverlay = requireNativeComponent('RNNaverMapPathOverlay');
const RNNaverMapPolylineOverlay = requireNativeComponent('RNNaverMapPolylineOverlay');
const RNNaverMapCircleOverlay = requireNativeComponent('RNNaverMapCircleOverlay');
const RNNaverMapPolygonOverlay = requireNativeComponent('RNNaverMapPolygonOverlay');
requireNativeComponent들을 불러오지를 못하는 것 같습니다. 

다시한번 노고에 감사드립니다.

**Comment by lhg1628** [comment]
넵... 이번에는 엑스포 안쓰고 npx react-native로 js만 써서 일단 테스트 해봤는데, requireNativeComponent 에러는 발생하지 않습니다.

하지만 라우팅시 튕기는 에러는 발생합니다.

디펜던시는 아래와 같습니다.

  "dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/drawer": "^5.4.1",
    "@react-navigation/native": "^5.1.5",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-nmap": "0.0.46",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },

**Comment by lhg1628** [comment]
뭔가 제가 이슈를 던졌는데, 결국 제목과 상이한 버그리포트가 된 것 같아서, 몇가지 더 첨부합니다.
버그를 재현한 gif와 환경을 첨부합니다. 갤럭시 s8 플러스 디바이스에서도 구동해본 결과 같은 버그가 발생합니다. 

저를 포함한 다른 분들의 편의를 봐주셔서 다시한번 감사드립니다.

![zoom_0](https://user-images.githubusercontent.com/51706260/79037054-f1691600-7c08-11ea-8bbb-8f6949cace00.gif)

<img width="197" alt="Screen Shot 2020-04-11 at 3 26 37 PM" src="https://user-images.githubusercontent.com/51706260/79037061-f9c15100-7c08-11ea-8f11-520a0438889e.png">

<img width="544" alt="Screen Shot 2020-04-11 at 3 26 48 PM" src="https://user-images.githubusercontent.com/51706260/79037063-fc23ab00-7c08-11ea-8afd-893f64ad638d.png">

<img width="464" alt="Screen Shot 2020-04-11 at 3 27 06 PM" src="https://user-images.githubusercontent.com/51706260/79037065-fd54d800-7c08-11ea-964a-741c8ee3d46f.png">

<img width="464" alt="Screen Shot 2020-04-11 at 3 27 58 PM" src="https://user-images.githubusercontent.com/51706260/79037071-0b0a5d80-7c09-11ea-9622-b345e2f7cdae.png">

**Comment by QuadFlask** [comment]
맵뷰 감추기/보이기로 테스트 해봤을 때 정상적으로 표시가 되는데 react-navigation BottomTabView에선 맵뷰 unmount가 이뤄지지 않는것 같습니다.
임시 해결책으로 아래와 같이 `unmountOnBlur`옵션을 주면 해당 스크린이 blur될때 스크린을 unmount 하게 되는데 이 경우 정상적으로 사용가능한것 같습니다.

```tsx
<Tab.Navigator screenOptions={{unmountOnBlur: true}}>
	{/* ... */}
</Tab.Navigator>
```

`react-navigation`의 `BottomTabView`의 구현을 살펴봐서 unmount 되지 않더라도 사용 가능한 방법을 찾아보겠습니다.

**Comment by lhg1628** [comment]
감사드립니다!

그런 문제라면 아마 탭 내비 말고도 드로워 내비에서도 동일한 증상이 나올 것 같습니다!

저도 한번 테스트 후 결과 공유해드리겠습니다.

**Comment by QuadFlask** [comment]
조금 찾아보니 탭뷰에서 뷰를 clipping 하게 되어있는데 이 경우 부모 뷰에서 보이지 않는 뷰를 제거하다보니 네이버맵뷰의 surface뷰가 제거되어 더이상 렌더링 할 수 없는 상태가 되버리네요. clipping 하는 뷰에 들어있어 clipping 되는 경우 해당 증상이 나오겠네요;;

**Comment by lhg1628** [comment]
아! 감사합니다. 이해가 완전히 된 것 같습니다.
개발자님 덕분에 많이 배웠습니다.

**Comment by QuadFlask** [comment]
버그를 수정한 0.0.47 버전을 배포하였습니다.
맵뷰를 직접 생성/삭제하는 방법이라 화면 전환시 맵뷰 상태가 보존되지 않아 부자연스러울 수 있습니다. 최대한 이전 맵뷰 상태를 복원하도록 하였습니다.

**Comment by lhg1628** [comment]
감사합니다!
