### ISSUE TITLE
ios 릴리즈 모드 테스트시 튕김 현상 발생

### ISSUE THREAD

**Issue by ryujw7** [QuadFlask/react-native-naver-map#22]
### Version of react-native-naver-map libraries

0.0.46

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

ios

### Expected behavior

네이버 맵 모듈 ios 실기기 적용

### Actual behavior

네이버 맵 ios 모듈 적용 이후 디버그모드로 에뮬에서 실행했을때는 지도가 잘 출력됩니다.
그런데 실기기 테스트를 위해 릴리즈모드로 실기기에 앱을 설치하면 앱 시작 시 바로 팅기는 현상이 발생합니다.

### Tested environment (Emulator? Real Device?)

에뮬 : iphone 11 ios 13.4
실기기 : iphone 8  ios 13.4.1

**Comment by QuadFlask** [comment]
혹시 어떤 에러 로그가 나오는지 알 수 있을까요? 제가 실기기 테스트를 할 수 없어 시뮬에 릴리즈 빌드를 해보았는데 정상작동해서 테스트하기 힘들듯 합니다ㅠ

**Comment by ryujw7** [comment]
> 혹시 어떤 에러 로그가 나오는지 알 수 있을까요? 제가 실기기 테스트를 할 수 없어 시뮬에 릴리즈 빌드를 해보았는데 정상작동해서 테스트하기 힘들듯 합니다ㅠ

> 아래 실기기 테스트 시 뜨는 로그를 올립니다.
@QuadFlask 
```
dyld: Library not loaded: @rpath/NMapsMap.framework/NMapsMap
  Referenced from: /private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/whatsubq
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: code signature invalid for '/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap'

	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: stat() failed with errno=25
	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: code signature invalid for '/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap'

	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: stat() failed with errno=1
	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: code signature invalid for '/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap'

	/private/var/containers/Bundle/Application/A0C3DBBA-3663-443F-A01F-F691E3988146/whatsubq.app/Frameworks/NMapsMap.framework/NMapsMap: stat() failed with errno=1
```

**Comment by QuadFlask** [comment]
@ryujw7 레포에 포함된 example을 실기기에서 실행해본 결과 정상 작동합니다. example을 참고해주세요.
프레임워크는 네이버맵 sdk일것 같은데요, pod을 통해 설치/링크가 제대로 안됐을 수 도 있겠네요;;

**Comment by ryujw7** [comment]
> @ryujw7 레포에 포함된 example을 실기기에서 실행해본 결과 정상 작동합니다. example을 참고해주세요.
> 프레임워크는 네이버맵 sdk일것 같은데요, pod을 통해 설치/링크가 제대로 안됐을 수 도 있겠네요;;

> 넵 참고해 보겠습니다.
> 더 알아보니 ios버전이 13.3.1버전으로 업데이트 되면서 실기기 디버그 테스트 시 발생하는 이슈가 있는 것 같습니다.
>[https://medium.com/@jinyoung.gist/rn-troubleshooting-thread-1-signal-sigabrt-err-after-update-ios-ver-to-13-3-1-766a47fdd1f](https://medium.com/@jinyoung.gist/rn-troubleshooting-thread-1-signal-sigabrt-err-after-update-ios-ver-to-13-3-1-766a47fdd1f)
