### ISSUE TITLE
안드로이드 스크린 이동 시 이전 스크린의 지도가 오버레이됩니다

### ISSUE THREAD

**Issue by shpongle2634** [QuadFlask/react-native-naver-map#27]
### Version of react-native-naver-map libraries
0.0.47

### Version of react-native
0.62

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
react-navigation v5 사용중입니다
스크린 Stack에 Screen A,Screen B가 있으며 각 스크린은 NMapView 가 있습니다

ScreenA -> Screen B 으로 navigate를 하면 
당연히 Screen B의 NMapView이 보이고,  A NMapView는 이전 스크린에 유지되어야 합니다

### Actual behavior
하지만 ScreenB 에서 B NMapView가 아닌 A NMapView가 화면에 오버레이되며, B NMapView는 A NMapView 아래에 렌더링 되는것이 확인되었습니다.

### Tested environment (Emulator? Real Device?)
Real Device(Samsung A310N0)  ENV=Dev

**Comment by QuadFlask** [comment]
https://github.com/nitaliano/react-native-mapbox-gl/issues/540
이 이슈와 비슷한것 같네요. 네이버맵뷰가 기본적으로 SurfaceView를 사용하는것 같은데, 
 다행히 sdk에서 `useTextureView()` 함수를 지원해서 수정할 수 있을것 같습니다. 
(대신 성능이 떨어진다고 하니 가능하면 옵션으로 선택할 수 있도록 추가하겠습니다.)

**Comment by QuadFlask** [comment]
`0.0.49`버전에 맵뷰 속성으로 `useTextureView`를 주시면 될것 같습니다.
