### ISSUE TITLE
iOS에서 Marker에 width와 height가 설정될 경우 공간을 차지하는 뷰가 생성되는 문제

### ISSUE THREAD

**Issue by vzts** [QuadFlask/react-native-naver-map#33]
### Version of react-native-naver-map libraries

v0.0.51
### Version of react-native
v0.60.5

### Platforms you faced the error (IOS or Android or both?)
iOS (Android에서는 이 현상이 관찰되지 않습니다)

### Expected behavior
하나의 마커에 대하여 별도의 View 가 생성되지 않고 마커 그래픽만 렌더링되어야 함

### Actual behavior
width와 height를 설정할 경우 마커 외에도 별도의 View들이 생성되어 왼쪽 1열을 위에서 아래를 투명하게 가리게 되고, 터치 이벤트를 가로 막아 네이버맵 자체의 버튼이 눌리지 않는 상황이 생깁니다.

### Tested environment (Emulator? Real Device?)
Real Device (iPhone SE 2020)
시뮬레이터에서 테스트해보진 않았지만 아마 같은 현상이 일어날 것으로 예상됩니다.

### Screen Shot

![image](https://user-images.githubusercontent.com/27868171/85602973-ddbb4080-b68a-11ea-95e6-cf045bb1f1b1.png)
![image](https://user-images.githubusercontent.com/27868171/85602155-0bec5080-b68a-11ea-96ab-e191b3492fe2.png)

example 앱 기준 바로 실행해서 인스펙터를 켜보면 첫번째 이미지처럼 나오고, width 와 height 가 있는 마커를 추가해보면 두번째 이미지처럼 아래로 쌓이게 됩니다. 어디를 고쳐야 할지 계속 살펴보고 있는데 감이 잘 안오네요... ㅠㅠ

**Comment by vzts** [comment]
아... 지금 다시 보니까 js에서 createElement 하는 부분이 의심되네요. 해결되면 PR 올려보도록 하겠습니다.

**Comment by QuadFlask** [comment]
제 환경의 시뮬레이터와 다른 형태로 나오는것 같네요;;
인스펙터가 이상한건지,,, 올려주신 이미지처럼 터치 영역 박스? 가 왼쪽에 나오지 않고 그냥 전체화면을 영역으로 잡네요;;;

**Comment by vzts** [comment]
으음 그럼 맵 영역이 터치가 안 되는 현상 같은 건 없으신가요?
이상하네요 저도 근시일내에 한번 다시 테스트해보겠습니다 ㅠ.ㅠ

**Comment by RyuuseiKang** [comment]
동일한 증상 <Marker/>에 style={{position: 'absolute'}}를 먹여 해결했습니다.
