### ISSUE TITLE
android에서만 coordinate 에러가 나요

### ISSUE THREAD

**Issue by geeeyeon** [QuadFlask/react-native-naver-map#35]
### Version of react-native-naver-map libraries

0.0.48

0.62.2

Android

naver 지도가 나오고, 선택한 좌표에 marker추가

error while updateing property 'coordinate' of a view managed by RNNaverMapMarker
라는 오류 메세지가 뜨면서 네이버 맵이 있는 화면 자체가 로드되지않음

안드로이드 환경 모두

![스크린샷 2020-07-15 오후 5 29 56](https://user-images.githubusercontent.com/47552192/87522686-e36fd900-c6c0-11ea-8e87-e219ee5743dd.png)

**Comment by QuadFlask** [comment]
테스트해볼 샘플 프로젝트가 있을까요?
