### ISSUE TITLE
iOS `RNNaverMapPolygonOverlay`에서 `didSetProps` 내 폴리곤 생성 호출이 작동하지 않는 문제

### ISSUE THREAD

**Issue by vzts** [QuadFlask/react-native-naver-map#38]
안녕하세요. 현재 제가 iOS 쪽에 폴리곤 내부 홀 기능을 구현하고 있는데 막혀서 주인장께 질문 드립니다.

먼저, hole 기능을 제공하는 네이버맵 SDK 인터페이스를 찾다보니 아래 2가지 방법이 있는 걸 발견했는데요:
1) `[NMGPolygon polygonWithRing:X interiorRings:Y]` 를 사용하는 방법
2) `[NMGPolygon addInteriorRing:Z]`를 모든 hole 에 대해 호출하는 방법 (호출하려면 polygon 이 미리 초기화되어 있어야 함)

어느 방법으로 구현하든, 기존 RNNaverMapPolygonOverlay 파일에서 coordinates(폴리곤 외곽) 와 holes(폴리곤 내부 홀)의 property 가 모두 설정이 된 후 실행이 되어야 합니다. 찾아보니 RCTView 의 `didSetProps` life cycle method 를 활용하면 모든 프로퍼티가 설정되었을 때에 코드를 실행할 수 있다고 하여, RNNaverMapPolygonOverlay 가 RCTView 를 상속받게 만들고, didSetProps 메서드를 추가해서 이 곳에서 polygon 을 초기화하는 코드를 넣으려고 하였습니다.

제가 테스트로 사용한 코드는 다음과 같습니다. 우선 didSetProps 라이프 사이클에서 폴리곤을 넣어줬을 때 잘 나타나는지 확인하고 싶어 최대한 미니멀하게 상수를 넣고, interiorRings도 일단 빼서 테스트를 진행했습니다.

준비:
RNNaverMapPolygonOverlay.h 에서 UIView 가 아닌 RCTView 를 상속 받게 수정
RNNaverMapPolygonOverlay.m 에서 아래 코드들로 수정

잘 동작하는 케이스:
(기존 setCoordinates 함수 내용을 수정)
```
- (void)setCoordinates:(NSArray<NMGLatLng *>*) coordinates {
    NSArray<NMGLatLng*> *coords = @[
        NMGLatLngMake(25, 115),
        NMGLatLngMake(25, 140),
        NMGLatLngMake(50, 140),
        NMGLatLngMake(50, 115),
    ];
  _realOverlay.polygon = [NMGPolygon polygonWithRing:[NMGLineString lineStringWithPoints:coords]];
}
```

동작하지 않는 케이스:
(setCoordinates 함수를 지우고, 아래 didSetProps 함수를 추가)
```
- (void)didSetProps:(NSArray<NSString *> *)changedProps {
    NSArray<NMGLatLng*> *coords = @[
        NMGLatLngMake(25, 115),
        NMGLatLngMake(25, 140),
        NMGLatLngMake(50, 140),
        NMGLatLngMake(50, 115),
    ];
  _realOverlay.polygon = [NMGPolygon polygonWithRing:[NMGLineString lineStringWithPoints:coords]];
}
```

디버그 해보았을 때, 양쪽 다 브레이크 포인트에 걸리고 실제 호출이 되는 것을 확인했으나, 첫번째는 폴리곤이 렌더링이 잘 되지만, 두번째에서는 렌더링이 되지 않습니다. 무언가 전체적인 렌더링 라이프사이클에서 잘못된 부분이 있지 않나 의심이 드는데, 제가 RN 지식이 미천하기도 하고(자료도 찾기가 정말 쉽지 않네요...ㅠㅠ) 전반적인 구조를 잘 파악하지 못하여서 혹시 짐작 가는 부분이 있으신지 이렇게 여쭤봅니다.

**Comment by QuadFlask** [comment]
아마 `didSetProps`가 해당 오버레이가 맵에 추가된 후 호출되는거라면 https://navermaps.github.io/ios-map-sdk/guide-ko/5-4.html 문서에 '추가 및 삭제' 설명에 따라 좌표가 설정되기 전에 추가되어 표시가 안되는것같네요.

제가 문제를 잘 이해했는지 모르겠는데, 폴리곤 외곽 좌표와 내부 홀 좌표를 받아서 폴리곤을 구성한 뒤 랜더링 하면 될것 같은데 내부 홀 좌표를 받을 수 있도록 하면 될까요?
굳이 다른 속성이 지정된 후 후처리로 할 필요는 없을것 같아서요;;
만약 한다면 JS단에서 한번에 외부,내부 좌표 객체를 받아 폴리곤을 구성할 수 있게끔 해야할것 같네요.

**Comment by vzts** [comment]
아...! 답변 감사합니다. 문서에서 놓친 부분이 있었네요. 말씀하신 부분이 맞는 것 같습니다.

사실 JS단에서 한번에 외부,내부 좌표 값 받으면 훨씬 쉽게 해결될 수 있는 문제긴 합니다.
기존 인터페이스를 해치지 않고 안드로이드 쪽 변경도 배제하고 하려다보니 이런 접근을 했던 것 같네요 ㅠ.^
근본적으로는 네이버맵 SDK의 iOS와 Android 호출방식이 달라서 이 문제가 생긴 것 같습니다 .

만약 JS단 입력을 바꾸는 방향으로 간다면, 기존 인터페이스
```js
export interface PolygonProps {
    coordinate: Coord[]
    outlineWidth?: number;
    outlineColor?: string
    color?: string;
    holes?: Coord[][];
    onClick?: () => void
}
```
에서
```js
export interface PolygonProps {
    coords: {
        exteriorRing: Coord[];
        interiorRings?: Coord[][];
    };
    outlineWidth?: number;
    outlineColor?: string
    color?: string;
    onClick?: () => void
}
```
식의 인터페이스로 바꿔도 괜찮을까요? breaking change 인 것 같아 조금 조심스럽네요 ㅎㅎ
괜찮다면 이번주 중에 구현 내용 올려볼 것 같습니다. 감사합니다!

**Comment by QuadFlask** [comment]
앗 제가 생각했던 방법은 인터페이스에선 따로 받도록 하고(coordinates, holes), 컴포넌트안에서 holes 속성 여부에 따라 분기를 하는걸 생각했습니다.
[react-native-maps](https://github.com/react-native-community/react-native-maps/blob/master/docs/polygon.md) 에서도 holes 를 따로 받아 처리하는걸 보니 비슷하게 하는게 좋을듯합니다ㅎㅎ

**Comment by vzts** [comment]
코드가 정확히 어디 들어가야 할 지 감이 잘 안 오네요.
제가 지금까지 파악하기로는 props 가 초기화되는 순서를 알 수 없고, 따라서 여러 개의 props 가 실제 어떻게 들어오는지 파악하려면 `didSetProps`를 써야 한다고 이해했는데 아닌가요?

**Comment by QuadFlask** [comment]
인터페이스를 유지하되, 
https://github.com/QuadFlask/react-native-naver-map/blob/8e89755d7e4cb25d820bb3718f4d3cac624c2361/index.tsx#L290
에서render() 함수 안에서 props를 통해 네이티브쪽 속성으로 넣어줄 때 합쳐서 넣어주면 된다는 의미였습니다.

**Comment by vzts** [comment]
아하! 완전 우문이였군요 ㅎㅎ; 라이브러리 JS에서도 처리할 수 있다는 사실을 간과했습니다.
포인터 감사드리고 한번 구현해보도록 하겠습니다~
