### ISSUE TITLE
안드로이드에서만 zoom 값이 14로 동작합니다.

### ISSUE THREAD

**Issue by trionsoft** [QuadFlask/react-native-naver-map#40]
### Version of react-native-naver-map libraries

"react-native-nmap": "0.0.51"

### Version of react-native

"react-native": "0.62.2"

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

지도 화면이 뜨자마자 해당 위치가 가까이 확대되어 보여야 합니다.
(zoom값 16 이상)

### Actual behavior

zoom 이 항상 14로 동작합니다.
이 문제는 안드로이드에서만 발생합니다.

render 메소드 안에서 NaverMapView 태그에 center 속성 안에 zoom 을 16, 17 이렇게 넣어도
onCameraChange 이벤트에서 zoom 값을 찍어보면 14로 찍히고, 지도 화면을 봐도 14로 적용되어 있습니다.
(iOS에서는 정상동작하기 때문에 차이가 확실히 구별됩니다.)

앱 화면에서 사용자가 손가락으로 확대/축소하는 건 정상동작합니다.

minZoomLevel 은 5
maxZoomLevel 은 20으로 사용하고 있습니다.
zoomControl 값은 true 로 사용중입니다.

### Tested environment (Emulator? Real Device?)

실제 기기 LGE-LM-Q815K (LG Q8 2018) 에 연결해서 테스트 중입니다.

**Comment by QuadFlask** [comment]
줌 설정시 tilt, beearing 값이 같이 넘어올 경우에만 적용되도록 되어있었네요.
0.0.52 버전으로 업데이트 하였습니다.

**Comment by JungWooLee1** [comment]
감사합니다. 해당 에러로 고생하고있었는데 해결법을 찾았네요!
