### ISSUE TITLE
zoom control 

### ISSUE THREAD

**Issue by hog225** [QuadFlask/react-native-naver-map#41]
### Version of react-native-naver-map libraries

0.0.51

### Version of react-native

0.63.1

### Platforms you faced the error (IOS or Android or both?)

Android

Issue 라고 하긴 그렇고 질문이 있는데요 혹시 zoom Control이 가능 한가요 ? 
animateToCoordinate 함수로 Camera를 이동시키고 있는데 이동 후 특정 줌 레벨을 같이 적용 하고 싶어서요 

animateToRegion 이라는 함수가 있긴 하지만 이렇게 되면 zoom level 값이 소수점으로 되더라고요 .. 
간략하게 zoom level을 줘서 Camera 이동 시키는 방법이 없는지 문의 드립니다.

**Comment by QuadFlask** [comment]
NaverMapView 컴포넌트의 center 속성에 좌표와 함께 zoom값을 넘겨주시면 될것 같습니다.
0.0.51 버전의 경우 tilt, bearing, zoom 값이 모두 존재할때만 적용되는 버그(#40)가 있었고 0.0.52 버전에서 수정하였습니다.
