### ISSUE TITLE
IOS 컴파일 에러

### ISSUE THREAD

**Issue by seonoh** [QuadFlask/react-native-naver-map#42]
### Version of react-native-naver-map libraries

0.0.52

### Version of react-native

0.63.2

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

컴파일 성공

### Actual behavior

git lfs를 설치했음에도 IOS 컴파일 시에 에러가 발생합니다.

### Tested environment (Emulator? Real Device?)

iPhone 11 에뮬레이터 

### Screen Shot

![스크린샷 2020-08-04 오후 4 22 15](https://user-images.githubusercontent.com/21157092/89264917-b0d95080-d66e-11ea-9abd-62fcedde4c5f.png)

**Comment by heyman333** [comment]
에러메세지를 스샷 말고 복사해서 올려주실 수 있으실까요?

**Comment by QuadFlask** [comment]
에러로 봐서는 네이버맵 sdk를 시뮬레이터용 바이너리가 아닌걸로 로드가 된것 같은데 `Pods`, `Podfile.lock` 을 삭제하신뒤 다시 `pod install`을 진행해보시겠어요?

**Comment by darron1217** [comment]
@QuadFlask 저도 동일한 증상입니다ㅜ
에러메세지는 아래와 같습니다

```
ld: warning: ignoring file /Users/darron/Documents/stormWorkspace/enre-app-parent/ios/Pods/NMapsMap/framework/NMapsMap.framework/NMapsMap, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NMFCameraPosition", referenced from:
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_METACLASS_$_NMFNaverMapView", referenced from:
      _OBJC_METACLASS_$_RNNaverMapView in libreact-native-nmap.a(RNNaverMapView.o)
  "_OBJC_CLASS_$_NMFCircleOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapCircleOverlay.o)
  "_OBJC_CLASS_$_NMFNaverMapView", referenced from:
      _OBJC_CLASS_$_RNNaverMapView in libreact-native-nmap.a(RNNaverMapView.o)
  "_OBJC_CLASS_$_NMGPolygon", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlay.o)
  "_OBJC_CLASS_$_NMGLatLngBounds", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapViewManager.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMFCameraUpdate", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapViewManager.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMGLatLng", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapCircleOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMFOverlayImage", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapMarker.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
  "_OBJC_CLASS_$_NMFPath", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
  "_OBJC_CLASS_$_NMFPolylineOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolylineOverlay.o)
  "_OBJC_CLASS_$_NMFMarker", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapMarker.o)
  "_OBJC_CLASS_$_NMGLineString", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolylineOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlayManager.o)
  "_OBJC_CLASS_$_NMFAlignType", referenced from:
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMFPolygonOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlay.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by darron1217** [comment]
아래 명령어로 pod로 최신버전 업데이트하니 정상적으로 작동했습니다
```
pod install --repo-update
```

의존성이 이전버전을 설치할수 있게 허용되어 있는건지, 아님 설치때마다 이렇게 업데이트를 원래 해줘야 하는건지 궁금합니다

**Comment by hoainamcr** [comment]
Hi @QuadFlask , I had found your comment link here, like @darron1217 
https://codecraft.tistory.com/entry/React-Native-ios-%EB%B9%8C%EB%93%9C%EC%8B%9C-Undefined-symbols-for-architecture-x8664-%EC%97%90%EB%9F%AC
But I can't resolve this issue to build IOS,

`react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.98 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`
`ld: warning: ignoring file /Users/apple/Projects/react-native-application/ios/Pods/NMapsMap/framework/NMapsMap.framework/NMapsMap, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_NMFNaverMapView", referenced from:
      _OBJC_METACLASS_$_RNNaverMapView in libreact-native-nmap.a(RNNaverMapView.o)
  "_OBJC_CLASS_$_NMGLatLng", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapCircleOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMFCircleOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapCircleOverlay.o)
  "_OBJC_CLASS_$_NMFCameraUpdate", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapViewManager.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMFOverlayImage", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapMarker.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
  "_OBJC_CLASS_$_NMFMarker", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapMarker.o)
  "_OBJC_CLASS_$_NMGLineString", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolylineOverlay.o)
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlayManager.o)
  "_OBJC_CLASS_$_NMFNaverMapView", referenced from:
      _OBJC_CLASS_$_RNNaverMapView in libreact-native-nmap.a(RNNaverMapView.o)
  "_OBJC_CLASS_$_NMGLatLngBounds", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapViewManager.o)
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "_OBJC_CLASS_$_NMGPolygon", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlay.o)
  "_OBJC_CLASS_$_NMFAlignType", referenced from:
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "__swift_FORCE_LOAD_$_swiftCoreMIDI", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBSDKShareKit)
  "_OBJC_CLASS_$_NMFPolygonOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolygonOverlay.o)
  "_OBJC_CLASS_$_NMFPolylineOverlay", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPolylineOverlay.o)
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBSDKShareKit)
  "_OBJC_CLASS_$_NMFPath", referenced from:
      objc-class-ref in libreact-native-nmap.a(RNNaverMapPathOverlay.o)
  "_OBJC_CLASS_$_NMFCameraPosition", referenced from:
      objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(AccessToken.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(Permission.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(Settings.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit in libFBSDKLoginKit.a(FBLoginButton.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit in libFBSDKLoginKit.a(LoginManager.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit, __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKShareKit , __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Du you have any way else to resolve this issue instead of `pod install --repo-update`, Or any I was wrong any way to build IOS.
Thanks you so much.

**Comment by QuadFlask** [comment]
@hoainamcr  Did you install git-lfs?

**Comment by hoainamcr** [comment]
@QuadFlask Yes, I did
![image](https://user-images.githubusercontent.com/8084862/101979298-80de3180-3c8e-11eb-956f-c9858e8d2aaf.png)

**Comment by darron1217** [comment]
@hoainamcr Did you remove Pod folder before `pod install --repo-update`?

**Comment by hoainamcr** [comment]
@darron1217 , Yes I did, and removed node_module to re-install, remove Pod folder and Podfile.lock, and pod install again
but I still got that issue
@QuadFlask  git-lfs -v on my laptop, 'git-lfs/2.12.1 (GitHub; darwin amd64; go 1.15.3)'

**Comment by darron1217** [comment]
What version did you install in npm?
Would you show your result of `npm ls react-native-nmap`?

**Comment by QuadFlask** [comment]
[check this out](https://medium.com/@edisonlo/ios-framework-file-was-built-for-x86-64-which-is-not-the-architecture-being-linked-arm64-linker-4d3780669aa3)

**Comment by hoainamcr** [comment]
Do we need any config from Header search path in Build setting
![image](https://user-images.githubusercontent.com/8084862/101979460-d7983b00-3c8f-11eb-8258-dbefe9bf3da6.png)
![image](https://user-images.githubusercontent.com/8084862/101979506-2ba31f80-3c90-11eb-9e5c-e0a7cfb13025.png)

**Comment by hoainamcr** [comment]
> [check this out](https://medium.com/@edisonlo/ios-framework-file-was-built-for-x86-64-which-is-not-the-architecture-being-linked-arm64-linker-4d3780669aa3)

Sorry @QuadFlask , I can't open your link

**Comment by QuadFlask** [comment]
@hoainamcr 
google it: `building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format`  or [stackoverflow answer](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios)

**Comment by hoainamcr** [comment]
Hi @QuadFlask and @darron1217. 
I found the solution to resolve this issue, that's updage the NMapsMap pod version from 3.7.0 to 3.10.0.
I sear that keywords is 'NMapsMap' in XCode by and change `s.dependency 'NMapsMap', '~> 3.7.0'` to `s.dependency 'NMapsMap', '~> 3.10.0'`.
And then I remove the pod folder, podfile.log and pod `install again`.
Thanks for your support. <3
![image](https://user-images.githubusercontent.com/8084862/102890235-adfcc200-448e-11eb-9c96-8eee12d3099e.png)

**Comment by QuadFlask** [comment]
@hoainamcr Thank you!
`0.0.56` will use updated NMapsMap version(3.10.1)
