### ISSUE TITLE
지도 클릭 위치에 Marker 표시하고,  과거 Marker 는 remove 하고 싶은데, 방법이 있을까요?

### ISSUE THREAD

**Issue by yannichoongs** [QuadFlask/react-native-naver-map#46]
### Version of react-native-naver-map libraries
"react-native-nmap": "0.0.52"

### Version of react-native

react-native: 0.63.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

N/A

### Actual behavior

지도 클릭 위치에 Marker 표시하고,  과거 Marker 는 remove 하고 싶은데, 방법이 있을까요?

### Tested environment (Emulator? Real Device?)

Android LG V30 device

**Comment by QuadFlask** [comment]
```js
function MyMap() {
  const [marker, setMarker] = useState({latitude: 0, longitude:0});

  return <NaverMapView style={{width: '100%', height: '100%'}}
                       center={{zoom: 16}}
                       onMapClick={setMarker}>
    <Marker coordinate={marker}/>
  </NaverMapView>
}
```

이런식으로 할 수 있을것 같습니다

**Comment by yannichoongs** [comment]
잘 되네요. 감사합니다.

아래와 같이 했더니, Double - ReadableMap 간 type casting err 가 발생해서 헤매는 중이었는데
덕분에 잘 배웠습니다~

const [currentLocation, setCurrentLocation] = useState({latitude: 38.564834, longitude: 127.977218});
    const locationHandler = (e) => {
        setCurrentLocation(e.latitude, e.longitude);
        //setCurrentLocation(e);
        console.warn('onMapClick', JSON.stringify(e));
    };

    return <>
        <NaverMapView style={{width: '100%', height: '100%'}}
                      showsMyLocationButton={true}
                      center={{...P0, zoom: 16}}
                      onTouch={e => console.warn('onTouch', JSON.stringify(e.nativeEvent))}
                      onCameraChange={e => console.warn('onCameraChange', JSON.stringify(e))}
                    onMapClick={e => locationHandler(e)}
                    useTextureView>
            <Marker coordinate={P0} onClick={() => console.warn('onClick! p0')} caption={{text: "test caption", align: Align.Left}}/>
            <Marker coordinate={P1} pinColor="blue" onClick={() => console.warn('onClick! p1')}/>
            <Marker coordinate={P2} pinColor="red" onClick={() => console.warn('onClick! p2')}/>
            <Marker coordinate={currentLocation} onClick={() => console.warn('onClick! currentLocation')} 
            image={require("./marker.png")} width={48} height={48}/>
