### ISSUE TITLE
Marker 내 caption 이 ios 에서 동작 하지않습니다

### ISSUE THREAD

**Issue by ompangchu** [QuadFlask/react-native-naver-map#49]
리액트네이티브 브릿지를 만들어주신 덕분에 네이버맵 잘 활용하고 있습니다.
사용 중에 아래 이슈 확인이 필요해보여 문의 드립니다.

### Version of react-native-naver-map libraries

 "react-native-nmap": "0.0.52",

### Version of react-native

"react-native": "0.63.3",

### Platforms you faced the error (IOS or Android or both?)

ios 

### Expected behavior

Marker 내 caption 값으로 text 를 넣었는데, 
맵상에서 안드는 보여지고, IOS는 안보입니다.

### Actual behavior

Marker 내 caption 이 ios 에서 동작 하지않습니다

### Tested environment (Emulator? Real Device?)

IPhone XS. (Android V35에서 동일코드로 caption 정상동작)

### Screen Shot
![IMG_2716](https://user-images.githubusercontent.com/71540456/98445123-5104b100-2159-11eb-9a97-718d3ceefcb6.jpg)

# src
render() {
    return (
        <NaverMapView
          ref={(ref) => this.map = ref}
          style={{width: '100%', height: '100%'}}
          showsMyLocationButton={true}
          useTextureView>
            {this.state.messages.map((message, index) => {
            let { latitude, longitude, text} = message;
              return (
                <Marker
                  ref={(ref) => this.marker = ref}
                  coordinate={{ latitude, longitude }}
                  caption={{text: text, align: Align.Top}}
                  ....

**Comment by kimyoungjae96** [comment]
현재 안드로이드만 제공하는 것으로 알고 있습니다 :)

**Comment by ompangchu** [comment]
답변감사드립니다.
ios도 marker에 text 를 꼭 입히고싶은데
방법이 없을까요?? :)

**Comment by QuadFlask** [comment]
iOS에도 추가해보도록 하겠습니다.

**Comment by ompangchu** [comment]
여력되시면 부탁드릴께요~

덕분에 nmap 잘 이용하고있습니다
감사합니다~

**Comment by QuadFlask** [comment]
0.0.54 버전을 배포하였습니다.

**Comment by ompangchu** [comment]
너무너무 감사합니다.
