### ISSUE TITLE
두개 이상의 View 생성시 지도표시가 좀 이상한데요.

### ISSUE THREAD

**Issue by warship2000** [QuadFlask/react-native-naver-map#5]
안녕하세요. 좋은 모듈을 만들어 주셔서 감사합니다.
해당 모듈을 이용하여 앱을 개발하고 있는데 문제가 있어 문의드립니다.

화면안에 작은지도를 보여주다가 버튼을 누르면 모달형태의 큰지도를 보여주게끔 하고싶은데
작은지도위에 큰지도를 표시할 경우 작은지도영역이 큰지도에 겹쳐서 표시됩니다.

![image](https://user-images.githubusercontent.com/46466613/70293944-3b8a5700-1825-11ea-8cf5-d7048920c58d.png)

해결방법이 있을까요?

**Comment by QuadFlask** [comment]
안드로이드인가요? 
surface뷰가 겹쳐서 표시 되는듯한데 어떤 모달 라이브러리를 사용하시는건가요? 
혹시 테스트 해볼 수 있는 샘플 프로젝트가 있을까요?

**Comment by warship2000** [comment]
안녕하세요. 오늘 해결했습니다. ^^;
react-native-modals 모듈을 사용하고 있었는데. 이 모듈의 Modal구현이 좀 특이한듯 합니다.
(onPress 이벤트도 무시되고 좀 이상하네요)

RN 기본 Modal 혹은 react-native-modal 모듈을 사용할 경우 문제가 없음을 확인했습니다.
감사합니다 ^^;

**Comment by warship2000** [comment]
안녕하세요. 오늘 해결했습니다. ^^;
react-native-modals 모듈을 사용하고 있었는데. 이 모듈의 Modal구현이 좀 특이한듯 합니다.
(onPress 이벤트도 무시되고 좀 이상하네요)

RN 기본 Modal 혹은 react-native-modal 모듈을 사용할 경우 문제가 없음을 확인했습니다.
감사합니다 ^^;
