### ISSUE TITLE
맵 이동을 막거나 disable 시킬 수는 없을까요?

### ISSUE THREAD

**Issue by bychung** [QuadFlask/react-native-naver-map#52]
### Version of react-native-naver-map libraries

0.0.54

### Version of react-native

0.62.2

### Actual behavior

안녕하세요. 네이버맵뷰를 열심히 써보고 있습니다.
그런데 궁금한 것이 있어서 질문드립니다.
1. 맵 이동을 막을 수는 없나요? 확대 축소(줌 컨트롤 버튼을 통해서)만 가능하게 하고요.
2. 맵 뷰를 disable (맵 이동 불가 및 터치 불가 등등, 세팅된 맵만 보여짐) 시킬수는 없는지요?

이와 같은 궁금증이 발생한 이유는, 
RN 스크롤 뷰 안에 맵뷰를 넣었을 때, 맵에 터치한 상태에서 위아래 이동을 하면 맵이 이동하는 것이 아닌 스크롤이 이동되게 되나, 좌우 이동을 하면 맵이 이동되는(좌우는 스크롤되지 않으므로) 비직관적인 행동이 발견되어서 그렇습니다.

**Comment by QuadFlask** [comment]
sdk 에서는 해당 기능을 지원하지 않는것 같습니다.
이동 영역 제한이 있는데 터치 이벤트가 사용돼서 말씀하신 부분에 대해선 해결책이 되지 않을듯 하네요. (혹시 sdk에서 지원하는 기능이 있다면 말씀해주세요)

임시방편으로 뷰 레이어를 하나 쌓아 터치가 맵뷰로 전파되지 않게 하는방법을 사용할 수 있겠네요.

**Comment by bychung** [comment]
> sdk 에서는 해당 기능을 지원하지 않는것 같습니다.
> 이동 영역 제한이 있는데 터치 이벤트가 사용돼서 말씀하신 부분에 대해선 해결책이 되지 않을듯 하네요. (혹시 sdk에서 지원하는 기능이 있다면 말씀해주세요)

이동 영역 제한이 있다고 하셨는데, 맵이동이 그럼 막히는 것인지요? 그정도면 목적달성이 됩니다.
스크롤 뷰에서 맵에 터치한 상태에서 위아래 이동시 스크롤이 이동되든 안되든 그건 상관이 없습니다. 좌우 이동시와 동일한, 즉 일관적인 상태면 좋을것 같거든요.
 
> 임시방편으로 뷰 레이어를 하나 쌓아 터치가 맵뷰로 전파되지 않게 하는방법을 사용할 수 있겠네요.

네 아직 시도는 안했지만, 이 방법은 저도 최후의 방법으로 고려중입니다.

**Comment by QuadFlask** [comment]
https://navermaps.github.io/android-map-sdk/guide-ko/3-2.html

문서 하단에 "카메라 영역 제한"이 원하시는 동작이 될지 모르겠습니다.

**Comment by bychung** [comment]
> https://navermaps.github.io/android-map-sdk/guide-ko/3-2.html
> 
> 문서 하단에 "카메라 영역 제한"이 원하시는 동작이 될지 모르겠습니다.

카메라 영역제한은 다른 의도의 기능인 것 같고, 제가 sdk 매뉴얼을 자세히 봤는데, 제가 애초에 원하던 기능을 찾았습니다.

https://navermaps.github.io/android-map-sdk/guide-ko/4-1.html
이 문서의 중간 쯤 '제스처' 파트가 있는데, 이 부분에 각 제스처 기능별로 활성화/비활성화를 선택할 수 있습니다.
제가 원하는 기능이라면, 아래에 해당될 수 있을 것 같습니다.

`
uiSettings.setScrollGesturesEnabled(false); // default: true임.
`

바쁘시겠지만, 복잡한 코딩은 아닌것으로 사료되어... 시간되실 때 추가해주시면 감사하겠습니다!!

**Comment by QuadFlask** [comment]
0.0.55 버전을 배포했습니다
