### ISSUE TITLE
error Failed to install the app.

### ISSUE THREAD

**Issue by Joseph-GM** [QuadFlask/react-native-naver-map#53]
안녕하세요? 이제 막 리엑트네이티브 배우는 초보인데요. 네이버 맵을 사용하고 싶어서 사용하려고 하는데 에러가 처음부터 나서 글 올립니다.
자세한 에러내용은 아래에 적어 놓을 게요. 제 환경이 문제 일 것 같은데 어디서 부터 문제인지 모르겠네요.
도와 주시면 감사하겠습니다.

### Version of react-native-naver-map libraries

Latest로 생각됩니다. (단순 npm install react-native-nmap --save 실행)
### Version of react-native

0.63.3 / 0.60.0 모두 실행
### Platforms you faced the error (IOS or Android or both?)

Android, (ios는 다른 에러)
### Actual behavior

README.MD에 있는 것을 다 따라서 할 때 에러가 발생해서, README.MD에 있는 것을 하나씩 하고 실행해 보았을 때, 처음부터 아래와 같은 메세지가 뜹니다. 
react-native init Navermaptest
npm install react-native-nmap --save
react-native run-android
실행하면 아래와 같은 메세지가 뜨네요.

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

**Comment by QuadFlask** [comment]
에러메시지를 보면 안드로이드 개발환경이 갖춰지지 않은것으로 보입니다.
메시지에 있는 링크를 따라 환경설정을 진행해보시겠어요?

**Comment by Joseph-GM** [comment]
위에 메세지에 있는 개발 환경다시 한 후 pod install 진행했더니, 더 이상한 Error가 나옵니다.
무엇이 문제 일까요?
================================================================
Auto-linking React Native module for target `Myfirstproject`: react-native-nmap
Analyzing dependencies
Downloading dependencies
Installing NMapsMap (3.7.0)

[!] Error installing NMapsMap
[!] /usr/bin/git clone https://github.com/navermaps/NMapsMap.git /var/folders/0w/61qkkw111_963jd8kgv6d5bw0000gn/T/d20201120-4255-14asov6 --template= --single-branch --depth 1 --branch release/3.7.0

Cloning into '/var/folders/0w/61qkkw111_963jd8kgv6d5bw0000gn/T/d20201120-4255-14asov6'...
Note: switching to 'd9b19effc03cf52f5dd4e4052ba0904f96a06e36'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Downloading framework/NMapsMap.framework/NMapsMap (141 MB)
Error downloading object: framework/NMapsMap.framework/NMapsMap (1338281): Smudge error: Error downloading framework/NMapsMap.framework/NMapsMap (13382817789a53f2230d12ef4be6f29b3a35495d8e17465049b8f237bc287ef4): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /private/var/folders/0w/61qkkw111_963jd8kgv6d5bw0000gn/T/d20201120-4255-14asov6/.git/lfs/logs/20201120T190258.971109.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: framework/NMapsMap.framework/NMapsMap: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Joseph-GM** [comment]
같은 환경에서 Google map인 react-native-maps로 ios와 android 둘다 잘 작동하는데, 뭐가 문제 일까요?

**Comment by QuadFlask** [comment]
에러 메시지에 의하면 
`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.` 
네이버맵 ios sdk 의 LFS 쿼터를 초과하여 다운로드 받지 못한것 같네요. 이 부분은 제가 해드릴 수 있는게 없네요;;

**Comment by Joseph-GM** [comment]
아~ data quota 가 있나 보네요... 그래도 실마리가 보입니다~ 감사합니다!

**Comment by Joseph-GM** [comment]
NmapMap 다운 받는데 문제가 있었나 보네요. 저 말고도 다른 분들도 같은 이슈를 해서 지금은 해결 되어서 성공 했네요 감사합니다.
