### ISSUE TITLE
ios 사용자위치버튼을 누르면 위치추적모드만 바뀌고 사용자 위치로 지도가 움직이지 않습니다

### ISSUE THREAD

**Issue by AMaster124** [QuadFlask/react-native-naver-map#56]
위치버튼을 누르면 위치추적모드는 바뀌는데 사용자 위치로 맵이 움직이지 않습니다.

사용하고 있는 버전 : "react-native-nmap": "^0.0.52"

내 코드 :

          <NaverMapView
            style={{
              width: '100%',
              height: Dimensions.get('window').height - 180,
            }}
            showsMyLocationButton={true}
            center={{
              latitude: centerLat,
              longitude: centerLng,
              zoom: 16,
            }}>
              <Marker
                coordinate={{latitude: lat, longitude: lng}}
                caption={{
                  text: selectedChild.name,
                  textSize: 14,
                  color: 'black',
                }}
              />
          </NaverMapView>

![IMG_5060](https://user-images.githubusercontent.com/66033254/104928509-15525700-59e6-11eb-88ee-aaa3106a9080.PNG)

**Comment by QuadFlask** [comment]
제가 태스트해보니 안드로이드 에뮬, iOS 시뮬레이터에서 해본 결과 정상 동작하고 있긴합니다.
위치 권한을 받아도 동일한가요?
이슈에 필요한 내욜을 최대한 적어주시면 좋을것 같습니다. 어떤 플랫폼에서 발생하는 문제인지 알려주세요.

**Comment by AMaster124** [comment]
답변 감사합니다. 위치권한이 문제인듯 하네요
위치권한을 info.plist 파일에만 주었었는데 React-Native에서는 따로 권한을 요청해야 하는것 같습니다. 
그런데 제 프로젝트에서는 백그라운드상태에서도 위치를 수집해야 하는지라 LocationAlways 권한을 요청해야 합니다. 
#55 이슈에서 보면 iOS에서는 위치권한을 LocationWhenInUse 로 요청하지 않을시 팝업이 뜨는데 LocationAlways 권한을 요청하면서 팝업이 뜨지 않도록 하는 방법은 없나요?
