### ISSUE TITLE
3.10.2 출시로 maven 주소가 바뀌었나요?

### ISSUE THREAD

**Issue by ZeroCho** [QuadFlask/react-native-naver-map#59]
[공식문서](https://navermaps.github.io/android-map-sdk/guide-ko/1.html)

기존 주소로 하니 Could not resolve 'https://navercorp.bintray.com/maps' 403 하면서 에러가 나서
maven { 'https://naver.jfrog.io/artifactory/maven/' }로 바꿨더니 됩니다.

**Comment by darron1217** [comment]
엇 제로초님 여기서 뵙네요ㅎ (리엑트방에서 도움 많이 받고 있습니다)

@QuadFlask 공식문서에서도 바뀐걸 보니 저장소 이동한게 맞는게 같습니다
README 업데이트 부탁드립니다 👍

**Comment by ZeroCho** [comment]
@darron1217 앗 안녕하세요. 포크뜨셨던 react-native-background-geolocation 썼는데 한국분이셨군요!

**Comment by darron1217** [comment]
@ZeroCho 엇 제 허접한 fork를... 앞으로도 잘부탁드립니다ㅎ
