### ISSUE TITLE
IOS에서 빌드시 문제가 발생했습니다.

### ISSUE THREAD

**Issue by clgh0331** [QuadFlask/react-native-naver-map#6]
먼저 좋은 모듈 제공해주셔서 감사합니다.

안드로이드의 경우에는 정상 동작 하지만,
IOS에선 다음과 같은 빌드 에러가 발생합니다.

제가 IOS 네이티브 언어쪽에 대한 지식이 없어서 해결을 못하고있습니다.
도와주실 수 있을까요

react-native : 0.60.5
react-native-nmap : 0.0.37

![스크린샷 2019-12-18 오전 10 40 12](https://user-images.githubusercontent.com/53758797/71048492-c69f1180-2182-11ea-9268-da7a75affdaf.png)

**Comment by QuadFlask** [comment]
pod 으로 의존성이 설치 되지 않을듯한데 혹시 테스트해볼 수 있는 샘플이 있을까요?

**Comment by clgh0331** [comment]
@QuadFlask 님 답변 감사합니다.
하단에 있는 주소에 올려놨습니다.
https://github.com/clgh0331/naver_map_error_sample

혹시 괜찮으시면 확인한번만 부탁드려도 될까요?

**Comment by jhs851** [comment]
react-native: 0.61.5
react-native-nmap: 0.0.37

저도 같은 에러가 발생합니다!

**Comment by QuadFlask** [comment]
아직 iOS 쪽 바인딩이 제대로 되어있지 않아 발생하는 문제같습니다.
임시로 프로젝트내 소스파일들을 복사하셔서 사용하셔야 할듯합니다ㅠ

**Comment by dw-Kwon** [comment]
> 아직 iOS 쪽 바인딩이 제대로 되어있지 않아 발생하는 문제같습니다.
> 임시로 프로젝트내 소스파일들을 복사하셔서 사용하셔야 할듯합니다ㅠ


위에 임시로 복사해서 사용한다는 말이 어떻게 해야하는지 가이드 부탁드립니다.  무슨 파일들을 어디다가 복사해서 쓰라는건지..

**Comment by nukbal** [comment]
3.3.0부터는  git-lfs가 없으면 네이버맵 파일을 다운로드 하지 않는 것 같습니다.

```
$ brew install git-lfs
// 프로젝트 폴더에서
$ git-lfs install
$ pod update
```
하니까 문제없이 빌드 되었습니다.

react-native: 0.61.5
react-native-nmap: 0.0.38

**Comment by ictechgy** [comment]
ios/Podfile의
target 'your_project_name' do 로 시작하고 end 로 끝나는 구문 안에  pod 'NMapsMap' 을 넣어주고 
pod update를 해주니까 되는거같긴 한데 ^^.. 잘 모르겠네요

**Comment by QuadFlask** [comment]
navermaps/ios-map-sdk#1
