### ISSUE TITLE
ScrollView 안에서 지도 상하 스크롤이 안 되는 문제

### ISSUE THREAD

**Issue by ZeroCho** [QuadFlask/react-native-naver-map#62]
### Version of react-native-naver-map libraries

0.0.56

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

ScrollView 안에서 지도 상하 스크롤이 되어야합니다.

### Actual behavior

지도가 좌우 스크롤만 되고 상하 스크롤이 되지 않습니다. nestedScrollEnabled를 켜도 그렇습니다.

### Tested environment (Emulator? Real Device?)

RealDevice 갤럭시 Z폴드2

**Comment by QuadFlask** [comment]
`0.0.58` 버전으로 배포하였습니다. 감사합니다!

**Comment by ZeroCho** [comment]
감사합니다~
