### ISSUE TITLE
com.naver.maps.map.overlay.Marker.setIcon(com.naver.maps.map.overlay.OverlayImage)' on a null object reference

### ISSUE THREAD

**Issue by goheroes** [QuadFlask/react-native-naver-map#63]
### Version of react-native-naver-map libraries
0.0.58

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
Android only
react-native-router-flux로 탭을 구현해서 사용하고있고, 슈퍼클러스터로 클러스터링을 구현해서 사용하고있습니다.

### Actual behavior

탭간 빠른 전환시 크래시 발생 (지도탭 -> 다른탭 -> 지도탭 ...)
지도탭을 빠져나가도 해당 컴포넌트는 렌더링이 유지되는데, 
다시 지도탭을 들어가면 안드로이드에서는 지도가 흰화면이 나왔다가 기본내장좌표(?) -> 원래 보던 좌표,줌(혹은 center)으로 카메라체인지 이벤트가 발생합니다.
다루는 마커의 수가 많다보니, 위 프로세스중 빠르게 마커를 그렸다 지웠다 하는 과정중 발생하는 오류인것 같습니다.

### Screen Shot
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.naver.maps.map.overlay.Marker.setIcon(com.naver.maps.map.overlay.OverlayImage)' on a null object reference
com.github.quadflask.react.navermap.RNNaverMapMarker.setOverlayImage

```

**Comment by QuadFlask** [comment]
`0.0.61`버전에서 맵뷰를 재사용하도록 수정했습니다. 랜더링을 유지하기 때문에 이 버그가 수정 되었을것 같습니다. 혹시 재발생한다면 다시 오픈해주세요. 감사합니다!
