### ISSUE TITLE
지도 나침반 동작 버그 문의

### ISSUE THREAD

**Issue by star4680** [QuadFlask/react-native-naver-map#67]
### Version of react-native-naver-map libraries

"react-native-nmap": "^0.0.55",

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

지도를 rotate 할 경우 왼쪽 상단에 나침반이 표시되고 터치 시 북쪽이 위로 가도록 지도의 위치가 조정 됨.

### Actual behavior

안드로이드의 경우 정상 동작 하는데 iOS 의 나침반 터치시 반응이 없습니다.

### Tested environment (Emulator? Real Device?)

iPhoneXS (실기기)

버그 수정이 가능할지 문의드립니다.

**Comment by QuadFlask** [comment]
iOS 시뮬레이터에선 정상 동작하는데 실기기에서만 나타나는 현상인가요?
