### ISSUE TITLE
[Android]하단탭이동시 이동시 지도 리렌더링되는 문제

### ISSUE THREAD

**Issue by zaeyeon** [QuadFlask/react-native-naver-map#73]
### Version of react-native-naver-map libraries

0.0.59

### Version of react-native

0.63.3

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

바텀탭(react-navigation의 bottom-tab)으로 지도탭에서 다른탭으로 이동후 다시 지도탭으로 이동할때 지도가 리렌더링되지 않고 이전의 지도가 바로 보임.

### Actual behavior

하단탭으로 지도탭에서 다른탭으로 이동후 다시 지도탭으로 이동할시 지도가 리렌더링됨
IOS는 리렌더링되지않고 기존의 요소가 바로보이는데 Android에서만 기존의 요소가 다시 리렌더링됩니다.

### Tested environment (Emulator? Real Device?)

emulator: Galaxy Nexus
device: Galaxy S7 edge

### Screen Shot
![ezgif com-gif-maker](https://user-images.githubusercontent.com/49143255/111743773-87072e00-88cd-11eb-8f10-a81ab90cd56f.gif)

**Comment by QuadFlask** [comment]
안드로이드 플랫폼에서 맵 객체가 화면에서 사라지면(뷰가 언마운트되면) 맵 객체를 제거하고 다시 뷰가 마운트 될때 새 맵뷰 인스턴스를 생성해서 표시하는 방법을 사용하고 있어 생기는 문제 같네요. 안드로이드 뷰 라이프사이클을 좀 살펴봐서 개선해야겠네요.

**Comment by QuadFlask** [comment]
기존 맵뷰를 재사용 하도록 수정해 `0.0.60`버전으로 배포하였습니다. 감사합니다!

**Comment by zaeyeon** [comment]
> 기존 맵뷰를 재사용 하도록 수정해 ~`0.0.60`~ `0.0.61`버전으로 배포하였습니다. 감사합니다!

넵 감사합니다!
