### ISSUE TITLE
[React Native - Android] pinColor 커스텀

### ISSUE THREAD

**Issue by Mins97** [QuadFlask/react-native-naver-map#78]
### Version of react-native-naver-map libraries

   "react-native-nmap": "^0.0.56",

### Version of react-native

"react-native": "^0.63.4",

### Platforms you faced the error (IOS or Android or both?)

React-Native

### Expected behavior

핀색깔을 바꾸고 싶은데 빨강색은 안되는건가요?

### Actual behavior

pinColor={data.id == selectedMaker?.id ? "blue" : "red"} // 실제폰에서  red가 주황색에 가까움.
red를 넣으면 자꾸 주황색이 뜨네요. 색을 더하는 연산인지..
직접 값을 바꾸려고 node_module도 건드려보고 있는데 해결 방법을 모르겠습니다.

### Tested environment (Emulator? Real Device?)

안드로이드

### Screen Shot

![스크린샷 2021-04-02 오후 9 47 50](https://user-images.githubusercontent.com/23623248/113416834-13047400-93fd-11eb-847e-90f84b78f6ee.png)

**Comment by QuadFlask** [comment]
[문서](https://navermaps.github.io/android-map-sdk/guide-ko/5-2.html) 에 보면 가산혼합으로 색상을 만든다고 합니다. 빨간색을 사용하기 위해선 마커 이미지를 따로 설정해야하네요. 현재는 따로 지원하진 않아 따로 마커 이미지를 만들어 사용하셔야할것 같습니다. 

추후에 속성값을  tint 와  color 로 나눠서 개발을 해야겠네요.
