### ISSUE TITLE
메모리 사용이 늘기만 합니다

### ISSUE THREAD

**Issue by dobo60** [QuadFlask/react-native-naver-map#81]
### Version of react-native-naver-map libraries

0.0.59

### Version of react-native

0.61.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Actual behavior

안녕하세요. 해당 모듈을 요긴하게 잘 쓰고 있습니다. 고맙습니다.

앱 다운 문제가 발생하여 올려주신 example에서도 발생하는지 확인을 해봤더니 동일한 현상이 발생하였습니다.
example 앱에서 하단 메뉴의 map, text를 번갈아가며 선택을 했을 때 map 메뉴에서 지도를 읽어오며 메모리가 증가를 합니다.
text로 이동해도 메모리는 내려가지 않습니다. 결국 앱은 다운되게 되었습니다.

### Tested environment (Emulator? Real Device?)

에뮬레이터 API 30

### Screen Shot

![nmap_crash](https://user-images.githubusercontent.com/76623293/114207886-d1913d00-9997-11eb-9a80-378c6d0b0e83.png)

**Comment by QuadFlask** [comment]
맵뷰를 재사용하고, 액티비티가 닫힐때 맵뷰를 제거하도록 수정하여 `0.0.60` 버전으로 배포하였습니다.
그래도 같은 문제가 발생한다면 새로 이슈를 만들어주세요. 감사합니다!
