### ISSUE TITLE
[Android]스크린 정중앙에 위치한 마커를 클릭하면 onClick 이벤트가 동작하지 않습니다.

### ISSUE THREAD

**Issue by newnorm** [QuadFlask/react-native-naver-map#82]
### Version of react-native-naver-map libraries

0.0.61
### Version of react-native

0.63.4
### Platforms you faced the error (IOS or Android or both?)

Android 
### Expected behavior

모든 마커에 대해 onClick 이벤트가 동작해야 합니다.
### Actual behavior

스크린 정중앙에 위치한 마커를 클릭하면 onClick 이벤트가 동작하지 않습니다. 
뭔가 이유가 될 만한 요소가 있을까요 ..?

```
          onClick={() => {
              console.log("clicked")
            }}     // 정중앙 마커 클릭시 콘솔 로그 찍히지 않음 
```

### Tested environment (Emulator? Real Device?)

모든 안드로이드 기기

**Comment by QuadFlask** [comment]
#33  과 관련있는 문제일 수 있겠네요.

**Comment by newnorm** [comment]
별도로 width 와 height 를 지정하지는 않았지만 보이지 않는 뷰가 나타나서 가로막는 것일 수도 있긴 하겠네요 ..!
https://github.com/QuadFlask/react-native-naver-map/issues/33 에서 @RyuuseiKang 님이 찾아낸 방법대로 커스텀 마커에 position absolute 를 적용했더니 뭔가 약간 개선된 느낌이 들기도 하고... 그런데 아직도 클릭이 안되는 경우가 종종 있습니다.
어려운 문제네요...!
답변 감사합니다! @QuadFlask

**Comment by QuadFlask** [comment]
흐음.... 혹시 예제 프로젝트에서도 발생하는 문제일까요? 다시한번 확인하보겠습니다.

**Comment by newnorm** [comment]
> 흐음.... 혹시 예제 프로젝트에서도 발생하는 문제일까요? 다시한번 확인하보겠습니다.

예제 프로젝트에서는 해보지 않았지만..

- `const RNNaverMapMarker = requireNativeComponent('RNNaverMapMarker');` 로 불러와서 렌더시킨 <RNNaverMapMarker/> 에 커스텀 이미지를 적용하지 않고 테스트했을 때에도 클릭이 안되는 문제상황이 발생했습니다. 
- 커스텀 이미지 적용 안한 상태에서 stype={{position: absolute}} 를 적용해도 클릭되지 않는 경우가 종종 있습니다. 
- 클릭이 안되는 영역은 대략 현재 선택된 마커를 꼭지점으로 하여 1cm 정도의 반지름을 가진 부채꼴 모양(?) 정도입니다. 

더 구체적인 재현경로를 알게 되면 다시 답변을 남기겠습니다.

**Comment by RyuuseiKang** [comment]
커스텀 이미지 적용 안하신 상태로 마커에 style={{top: -10000}} 적용해서 우회하는 방법도 있을 것 같습니당

**Comment by newnorm** [comment]
인스펙터로 확인해봤습니다. 
화면 정중앙에 가로 100, 세로 30 크기의 직사각형 뷰가 생기네요
