### ISSUE TITLE
[사용방법] 카메라 이동 관련

### ISSUE THREAD

**Issue by judaihyun** [QuadFlask/react-native-naver-map#89]
### Version of react-native-naver-map libraries

0.0.62

### Version of react-native

0.640

### Platforms you faced the error (IOS or Android or both?)

현재는 안드로이드만 확인했습니다.

### Expected behavior

center props에 좌표를 넘겨줄때마다 카메라가 이동되어야 합니다.

### Actual behavior

마커를 클릭 시 카메라가 해당 마커 중앙으로 이동하게끔 하려고 합니다.
그러나, 단 1회만 수행되고 수행되지 않습니다.
1. 최초 지도 로드시 center={서울시청(useState로 관리)} 로 해두었습니다.
2. 그리고 제스처를 통하여 다른 지역을 관찰 후 클릭 시 center의 좌표 state를 setState 액션차형 카메라를 이동시킵니다.
3. 두번째는 이동되지 않습니다.

이에 대한 실험(?)을 해보았는데요.
[방식] 해당 서울시청에 대한 좌표는 useState에 넣어둔 후, setState하여 좌표를 전달하는 방식으로 둔 상태에서

1. 이벤트(버튼등)를 받을때마다 setState에 새로운 좌표를 넣으면 버튼을 누를때마다 
마커의 위치도, 카메라의 위치도 정상적으로 전환됩니다. 
그러나, 같은 좌표, 같은 zoom level은 단 1회만 이동하고 움직이지 않습니다.

2. (1)과 같은 방식으로 버튼을 누를때마다 좌표는 유지한체 zoom level만 변경하면 정상적으로 전환됩니다.

일단 react의 state 특성인 값이 변하지 않았으므로, 렌더하지 않는것 때문인데요.
결국 무언가 map에 신호(?)를 줘서 카메라를 이동시켜야하는데 react에서는 마땅히 방법이 떠오르지 않습니다..
그래서 결국 제가 궁리한것이 위에 말한것처럼 좌표나 zoom level을 바꾸어야 state가 change되면서
map props의 center에 좌표가 변경 처리(?)가 되면서 카메라가 이동됩니다.

이렇게 해도 IOS나 다른기기, 그리고 비동기의 특성으로 인한 성능때문에
타이밍이 안맞던지해서 작동이 안될일이 있지 않을까 하는 염려도 있습니다.

이 문제는 어떻게 처리를 하셨는지 여러분들의 도움이 필요합니다.

즉,
지도상에 단 하나의 마커를 표출,
해당 마커의 위치로 center에 좌표 넘겨줌,
지도 정상 수행 확인.
제스처로 카메라 이동,
다시 해당 마커를 클릭 시 카메라 이동되지 않음.

입니다.

마커가 1개가 아니라 다수인경우,
이 다수를 순서대로 중복없이 누른다면
state가 동일하지 않으니, 당연히 정상처리 됩니다...

최대한 두번 질의 하실일 없이, 최대한 풀어썻습니다.
도움 부탁드립니다.

**Comment by QuadFlask** [comment]
제 경우 두가지 방법을 사용했었는데요,
1. `center`에 할당할 좌표에 랜덤값으로 굉장히 작은 값을 더하거나 빼서 다른 값을 넘겨주는 방법 (`Number.EPSILON` 정도 되는 값을 랜덤으로 더하거나 빼기)
2. `ref`을 받아오고 카메라 이동 메소드 호출( `animateToCoordinate` 메소드로 카메라 위치를 변경할 수 있습니다)

`center`는 초기 카메라위치 설정 용도로만 사용하시고 2번째 방법을 사용하는것이 좋을것 같습니다.

**Comment by judaihyun** [comment]
> 제 경우 두가지 방법을 사용했었는데요,
> 
> 1. `center`에 할당할 좌표에 랜덤값으로 굉장히 작은 값을 더하거나 빼서 다른 값을 넘겨주는 방법 (`Number.EPSILON` 정도 되는 값을 랜덤으로 더하거나 빼기)
> 2. `ref`을 받아오고 카메라 이동 메소드 호출( `animateToCoordinate` 메소드로 카메라 위치를 변경할 수 있습니다)
> 
> `center`는 초기 카메라위치 설정 용도로만 사용하시고 2번째 방법을 사용하는것이 좋을것 같습니다.

2번의 경우, props가 아니고 메소드였었나요??

**Comment by QuadFlask** [comment]
NaverMapView  컴포넌트에 메소드가 있습니다.

https://github.com/QuadFlask/react-native-naver-map/blob/9fe5eccab510b90eb5694e688d0958f315ab43be/index.tsx#L131

```js
const ref = useRef(null);
return <NaverMapView ref={ref}>
  <Marker coordinate={P0} onClick={() => ref.animateToCoordinate(P0)}/>
</NaverMapView>
```
이런식으로 사용할 수 있습니다.
