### ISSUE TITLE
Marker 클릭 이벤트 추가 좀 부탁드립니다. 

### ISSUE THREAD

**Issue by hoho721** [QuadFlask/react-native-naver-map#9]
안녕하세요. 만들어주신 라이브러리 정말 감사합니다. 
다름이 아니라 지도에서 마커 클릭시 건물 정보를 화면에 출력해주는 부분을 구현해야 해서요...
아직 리액트 네이티브 초보라 브릿지 부분을 시간내에 공부해서 구현하기가 벅차서...부탁좀 드릴수 있을까요?

**Comment by obzect7** [comment]
저도 라이브러리 정말 잘 사용하고 있는데 마커 온클릭시 주소정보 출력을 위해 onTouch 이벤트가 필요한 상황입니다. ㅠㅠ

**Comment by QuadFlask** [comment]
0.0.39버전에 안드로이드에 한해 onClick 이벤트를 추가하였습니다.

**Comment by QuadFlask** [comment]
0.0.40 버전에 ios에도 추가하였습니다.
