### ISSUE TITLE
[Android] 뒤로 가기를 누른 후 null object reference 에러가 발생합니다.

### ISSUE THREAD

**Issue by Jwlee134** [QuadFlask/react-native-naver-map#98]
### Version of react-native-naver-map libraries

0.0.63

### Version of react-native

0.64.1

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

뒤로 가기를 눌러 뒤로 간 후에 오류가 없어야 합니다.

### Actual behavior

뒤로 간 후에 Attempt to invoke virtual method 'void com.github.quadflask.react.navermap.RNNaverMapView.on.SaveInstanceState(android.os.Bundle)' on a null object reference 에러가 발생되며 콘솔에는 뜨지 않습니다. 여기서 Dismiss를 클릭해도 화면 상의 아무것도 클릭이 되지 않습니다.
본 프로젝트에서 저런 문제가 발생하여 혹시 몰라 샘플 프로젝트를 새로 생성 후 다시 시도해봤는데 같은 에러가 뜹니다.

### Tested environment (Emulator? Real Device?)

Both

### Screen Shot

https://user-images.githubusercontent.com/67630303/119960363-d6f62580-bfdf-11eb-8441-4de11b1081f3.mov

<img width="457" alt="스크린샷 2021-05-28 오후 6 18 47" src="https://user-images.githubusercontent.com/67630303/119961577-2e48c580-bfe1-11eb-89f0-935fe959d12d.png">

**Comment by QuadFlask** [comment]
재현할 수 있는 코드를 올려주시면 테스트해보겠습니다. 제 환경에서 본 레포에 있는 샘플 프로젝트에서는 발생하지 않네요;

**Comment by Jwlee134** [comment]
https://github.com/Jwlee134/SampleProject 위 영상에서 사용된 레포지토리입니다.

**Comment by QuadFlask** [comment]
`0.0.65`버전에서 수정하였습니다. 
최근 RN 안드로이드쪽 코드에서 뭔가 다른 동작이 있나 싶네요. detachWindow가 여러번 호출되는것 같은데 임시로 null 체크를 추가하여 수정하였습니다.
